### ISSUE TITLE
Roomfinder shows wrong locations

### ISSUE THREAD

**Issue by xsrf** [TUM-Dev/Campus-Android#1182]
## Steps to Reproduce

1. Search for a room, e.g. "0.01.24"
2. Search for the same room in TUMonline and click on the location
3. compare locations shown on the picture

## Expected Result

locations should match

## Actual Result

locations don't match

## Problem

locations don't match

## Suggested Enhancement :sparkles:

fix it ;) I guess TCA only shows the location of the building

### Environment
* Phone: Nexus 5X
* OS version: ...
* TUM Campus App version: 2.3
* Language: de

**Comment by xsrf** [comment]
Buidl

![2018-10-29 21 57 06](https://user-images.githubusercontent.com/8081353/47725409-ce3ae880-dc58-11e8-8ed6-6297a1c9bc06.png)

**Comment by Honeybyte** [comment]
It seems like that the bug is in the the server which is redirecting to the actual map URL. Searched for room 1200B:

Result in version 2.1-dev
`ImageViewTouchFragment: room finder url: https://tumcabe.in.tum.de/Api/roomfinder/room/defaultMap/1200B@0502`
After switching maps
`ImageViewTouchFragment: room finder url: https://tumcabe.in.tum.de/Api/roomfinder/room/map/1200B@0502/12`

Result in recent version 3.2-dev
`ImageViewTouchFragment: room finder url: https://tumcabe.in.tum.de/Api/roomfinder/room/defaultMap/1200B@0502`
Switching maps not possible in recent version as menu is not shown (intended?)

Both URLs (…/room/defaultMap/… and  …/room/map/…) are redirecting to the same URL https://portal.mytum.de/campus/roomfinder/getBuildingMap?b_id=0502&mapid=12
But the non default one should redirect to https://portal.mytum.de/campus/roomfinder/getRoomMap?mapid=12&roomid=1200B@0502

**Comment by kordianbruck** [comment]
@Honeybyte thanks for pointing this out. That the map selection is not visible is certainly a separate issue. I'll follow up once I had time to check out the backend and data stored there.
