### ISSUE TITLE
Room maps not loading

### ISSUE THREAD

**Issue by jacqueline8711** [TUM-Dev/Campus-Android#1338]
Maps are loaded ("Sorry, something went wrong")
Tested on current develop and last release. 

Example call [https://tumcabe.in.tum.de/Api/roomfinder/room/availableMaps/101%25405620](https://tumcabe.in.tum.de/Api/roomfinder/room/availableMaps/101%25405620)
```
Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/tca-portal/App/Functions.php on line 119

Warning: file_get_contents(): Failed to enable crypto in /var/www/tca-portal/App/Functions.php on line 119

Warning: file_get_contents(http://portal.mytum.de/campus/roomfinder/): failed to open stream: operation failed in /var/www/tca-portal/App/Functions.php on line 119

Notice: Undefined offset: 1 in /var/www/tca-portal/App/Modules/Api/Room.php on line 165

Notice: Undefined index: ze in /var/www/tca-portal/App/Modules/Api/Room.php on line 232
Error: empty URL for xml rpc call supplied
```

**Comment by jacqueline8711** [comment]
I’m quite sure this worked when we introduced Picasso. I don’t know the
file type though. Since it’s most likely the backend I’ll try to fix it
before the semester starts.

**Comment by CommanderStorm** [comment]
Works on Older Android Versions

- [Android 5.1.1, App-Version 3.4, Huawei Y6, no VPN/...], where it DOES work
Proof:
![WhatsApp Image 2019-10-23 at 10 16 20](https://user-images.githubusercontent.com/26258709/67381524-54e48600-f58c-11e9-9c5b-f9c6147f1c43.jpeg)


- [Android 9, App-Versin 3.4, Samsung S8, no VPN/...] and here it does NOT work
Proof:
![Screenshot_20191023-120040_Campus](https://user-images.githubusercontent.com/26258709/67381922-f2d85080-f58c-11e9-8354-c30cd5a80fc8.jpg)

**Comment by julianostarek** [comment]
@CommanderStorm Can't confirm. Room 02.13.007, too, fails for me on a SDK 22 emulator. 

I've spent some time diving into the thrown exceptions and it seems there's something funky about one of the servers' SSL certificates. The SSL handshake fails with the following (standard) exception:

`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

I'm no ssl expert hence I suppose this might be a hint for you @jacqueline8711 . Has the SSL configuration of the backend changed recently? Could it be that the certificate is self-signed? We'd have to implement custom handling in case to correct this issue.

**Comment by kordianbruck** [comment]
@julianostarek you have a URL so I know which server I should go and check? There are some Certificate Pinnings in the App, but I'm pretty sure those should not affect the maps download.

**Comment by julianostarek** [comment]
@kordianbruck An example would be the room tested above, i.e. `https://tumcabe.in.tum.de/Api/roomfinder/room/defaultMap/02.13.007%405613`.
Because OkHttp successfully proceeds past the first HTTP/302 cross-protocol redirect to
`http://portal.mytum.de/campus/roomfinder/getBuildingMap?b_id=5613&mapid=142`, which in turn redirects to itself as https, `https://portal.mytum.de` seems to be at fault.

**Comment by kordianbruck** [comment]
So if you check `ImageViewTouchFragment` there we use Picasso to download the picture from that URL. What I could do on the server side is to cache these pictures and instead of redirecting them, directly serving them from our server. That would be possible. 

If you check `ApiHelper` we add some SSL pins to OkHttpClient - it might be a side effect, that the client is also affecting picasso picture downloads. 

Would you happen to have the full stacktrace? The error message posted by @jacqueline8711 does not seem to be the same issue.

**Comment by kmodexc** [comment]
Is this fixed? I have the same Problem.

**Comment by CommanderStorm** [comment]
No, I doubt, that this is fixed. If you want you can jump into it.
I am currently working on [a new Roomfinder](https://github.com/TUM-Dev/navigatum).
It should be eazier to implement, assuming that https://github.com/TUM-Dev/navigatum/pull/79 is merged soon-ish
