### ISSUE TITLE
Showing grade for exam that isn't graded yet

### ISSUE THREAD

**Issue by phixxx5** [TUM-Dev/Campus-Android#1352]
## Steps to Reproduce

1. Write exam "Numerisches Programmieren"
2. Look into Grades in the android app before it's graded

## Expected Result
Don't show grades for exams that aren't graded

## Actual Result
Shows a 5,0 for my exam

## Problem
I almost suffered a heart attack when I saw it

### Environment
* Phone: Honor 8
* OS version: 7.0
* TUM Campus App version: v3.4
* Language: English

**Comment by pfent** [comment]
That's an issue with the TUMonline API we use in combination with TUMexam. TUMexam defaults to export a '5,0' for ungraded exams, even for exams that weren't graded yet, since that's the "technically correct" grade. TUMonline internally has a flag that can be used to set grades as visible for students, but the TUMonline XML API returns '5,0' instead of something sensible like NULL.

I already complained about this bad UX, maybe @xsrf knows more about the current state

**Comment by xsrf** [comment]
Short update: CAMPUSonline supplied instructions on how to update the API but I haven't had time to test it yet

**Comment by xsrf** [comment]
Issue MAY be fixed now. The API should now return null / an empty value.

**Comment by pfent** [comment]
@phixxx5 can you maybe test and confirm that the grades now show correctly? Or better don't show.

Or is your numprog exam already graded?

**Comment by phixxx5** [comment]
@pfent it's not showing a grade anymore seems like it's fixed. Thanks!
