### ISSUE TITLE
Figure out why news are currently failing

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#1362]
Seems there haven't been new news for some time. Probably something is broken in the backend again *sigh*

**Comment by joschahenningsen** [comment]
I managed to locally fix this, I found these issues:

https://github.com/TUM-Dev/Campus-Android/blob/b75948f09c0e9fd4511dfba7b0bbdb1afbeab0c3/app/src/main/java/de/tum/in/tumcampusapp/component/ui/news/NewsController.kt#L89
- getLastId returns "" if there are no news saved on the device. The api however returns an empty list for /news/ - without an id. Is this intended? I feel like new users will never get news.

- Some news from the API have dates like this: `0000-00-00 00:00:00` which can't be deserialized. (Months needs to be >=1, <=12) This can be sanitized in `DateSerializer.kt` but this might also happen in the backend?

My changes feel hacky because I just fallback to 1 as the last news id and I use DateTime.now() for these dates.  Should I open a PR or do you have a better solution in mind?

**Comment by joschahenningsen** [comment]
News should work, related issues can be opened here: https://github.com/TUM-Dev/Campus-Backend
