### ISSUE TITLE
Opening hours with '\n' in time field

### ISSUE THREAD

**Issue by SiKreuz** [TUM-Dev/Campus-Android#1369]
## Steps to Reproduce

1. Open Opening Hours Activity
2. Go to the detailed view of a sub section
3. The time values are sometimes more than just a simple one line string, but with multiple lines and `\n`. Probably received like that from the API and not properly formatted.

![image](https://user-images.githubusercontent.com/48913164/100014879-5576ce00-2dd7-11eb-9432-5b8df0bd2e60.png)

### Environment
Phone: OnePlus 5T
OS version: OxygenOS 10.0.1
TUM Campus App version: v3.9-dev
Language: German & English

**Comment by jlnstrk** [comment]
Can confirm it's the server who's at fault here. The newlines within the [json](https://tumcabe.in.tum.de/Api/openingtimes/de) vary among literal "\\\n", "\\/n" and "\n". Both 1 and 2 are essentially wrong [following ECMA 404](https://www.ecma-international.org/publications/standards/Ecma-404.htm). Number 1 is where this issue appears, number 2 is "fixed" by the weird string-replace stuff happening [here](https://github.com/TUM-Dev/Campus-Android/blob/b75948f09c0e9fd4511dfba7b0bbdb1afbeab0c3/app/src/main/java/de/tum/in/tumcampusapp/component/ui/openinghour/OpeningHoursDetailFragment.java#L85).

Gson (correctly) interprets the "\\\n" in the json as literal "\\n", "\\/n" as "/n", and "\\n" as an actual newline character. While number 1 probably occurs because of a single escaping backslash too many (in the json source), I don't really see why number 2 would happen, even though it seems to be the most frequent by far.
Other json elements are also affected (like "infos").

**Comment by joschahenningsen** [comment]
Opening hours are simply stored in the backend and retrieved by the app, we can easily replace any inconsistencies there I suppose. @SiKreuz you can open this in https://github.com/TUM-Dev/Backend if you want.

**Comment by CommanderStorm** [comment]
closing, I created an [issue over there ](https://github.com/TUM-Dev/Backend/issues/8)
