### ISSUE TITLE
KinoDetailsFragment shows details for wrong event

### ISSUE THREAD

**Issue by joschahenningsen** [TUM-Dev/Campus-Android#1374]
## Steps to Reproduce

1. Go to "Booked Events"
2. Click on any event
-> No matter what event was clicked, details for captain marvel are shown.

## Suggested Enhancement :sparkles:
I think this is caused by the KinoComponent injecting a wrong movie ID so the Fragment defaults to the first Film. I can investigate this.

### Environment
* Phone: OnePlus 6T
* OS version: Android 10
* TUM Campus App version: 3.9-dev
* Language: English

**Comment by jlnstrk** [comment]
This seems to be related to an inconsistency in how tumcabe returns/the TCA fetches events vs. kinos. The local kino table only ever receives tuples dating from onwards of 10/10/19 (i.e. id 149), which happens to be Captain Marvel, matching the result set of https://tumcabe.in.tum.de/Api/kino/. The events table only receives earlier events, with the latest one (High School Musical, kino id 146) dating to 9/7/19. This in turn matches the result set of https://tumcabe.in.tum.de/Api/event/list.

Kino positions for the detail pager are looked up by  counting the number of local kinos that are older than the argument's (which was an event tuple after all) kino id.  If this id itself isn't even present, a 0 is returned and Captain Marvel is shown.

This brings up a few questions, namely

- Why are we paging only kinos in a detail view that is reached from a superset of those?
I'm presuming this because of the distinction between events and kinos. This appears to be unexpected behavior from a UX perspective.

-  Why is the events endpoint returning the old (and only the old) stuff?
I mean, the two sets are even disjoint, which is fairly odd.

- I'm not familiar with the tumcabe api spec (where does one find that one anyway?), but I wonder if there's a way to page results in specified date ranges? If we're fetching data from two endpoints we'd obviously have to use this to stay consistent, thus to make sure all local (kino event or kino) tuples have a counterpart in the respective other table.

**Comment by kordianbruck** [comment]
Thanks @jlnstrk for looking this up. Unfortuantely the story isn't so easy here. Let me give a little bit of context from the backend: the Kino feed is the RSS feed coming from the TU film website. This is automatically fetched and updated as soon as they add them.

The event endpoint however is completely separate, due to it being build in a more general matter, to open up the options for other events that used to happen. So there isn't really a direct relationship between events <=> kino items. I think we tried to hack around this by matching on the movie title somehow.

We should never rely on the number of events/kino items being returned, as some kinos never have an event matched (not all had ticket sales online).

Given I don't know the newest folks that are running the tufilm now, I'm not even sure we'll have any more movies show up in the next 1-2 semesters. So I doubt its worth investing time here.

**Comment by kordianbruck** [comment]
We haven't had any bookings via TUFilm in a long time and won't have them any time soon again probably. So this sounds obsolete.
