### ISSUE TITLE
Add KTX

### ISSUE THREAD

**Issue by kordianbruck** [TUM-Dev/Campus-Android#646]
https://www.heise.de/developer/meldung/Android-Erweiterung-soll-Entwicklung-mit-Kotlin-vereinfachen-3961114.html

**Comment by psukys** [comment]
*Use KTX
Also, it's in *preview* at the moment, is it good to deploy this?

**Comment by kordianbruck** [comment]
Nah, this more a reminder :+1:

**Comment by i-walker** [comment]
Adding KTX seems to break ActivityForDownloadingExternal and other classes invoking the .observe function in utils/Extension.kt

fun <T> LiveData<T>.observe(owner: LifecycleOwner, callback: (T?) -> Unit) {
    observe(owner, Observer<T> { value -> callback(value) })
}

I suggestion reimplementing observe Funktion. // creates quite a lot of repetitive work

Or something else. 

Does this function do anything more than syntactic suggering, maybe there is a way out? 

I am still not sure why importing ktx brings these errors.

**Comment by i-walker** [comment]
> It's in _preview_ at the moment, is it good to deploy this? Is there a general guide on how to replace stuff with KTX (that is, what's available)?
@psukys 
This is everything I got. It's worth giving it a look, whenever there seem to be too many Extension functions.
I suggest using it for later development because it does not leverage anything. Only a common syntax and minimize extension functions:
https://kotlinexpertise.com/android-ktx-kotlin/
https://www.youtube.com/watch?v=LP3PaPrIFHo
https://medium.com/exploring-android/exploring-ktx-for-android-13a369795b51
https://www.kotlindevelopment.com/even-sweeter-android-ktx-kotlin/
https://kotlinexpertise.com/android-ktx-kotlin/
https://medium.com/mindorks/android-ktx-a-new-library-by-android-that-you-need-to-try-today-4b3b74d5d450
https://smartsoftware247.com/android-ktx-tutorial-getting-started/

**Comment by kordianbruck** [comment]
@i-walker thanks for looking into this. Can you maybe publish your work so far on this issue on a respective branch? Maybe somebody from the team can take a look in the future.

**Comment by jacqueline8711** [comment]
Was added in one of the Kotlin conversion PRs
